### ISSUE TITLE
For Hifilabs frontend; transform old crawl into @music-os/schema complicit data structure

### ISSUE THREAD

**Issue by TimDaub** [music-os/music-os-data#1]
## Scope

- Until Friday, Hifilabs wants to ship music OS, a news feed for music NFTs. A comparable music NFT newsfeed could be https://futuretape.xyz/ just to get an idea
- HifiLabs and music-os have agree to collaborate with the interface for collaboration being the `nfts.json` file in this repository.
- Essentially, a process from HL downloads `nfts.json` and ingests it into a [strapi](https://strapi.io/) instance. strapi then provides a graphql interface for HL's frontend newsfeed.

## Problem

- If you look into `nfts.json` currently, you'll see that only two music NFTs are listed there. Please note, though, that the schema they're listed in is complicit to the latest version of [music-os-schema](https://github.com/music-os/music-os-schema).
- However, [an earlier crawl](https://github.com/music-os/music-os-data/commit/e985560b5808a731ad58c6e6f2ace6a709e88bfb) had much more data, but none that was compliant with music-os-schema.
- Since we urgently need the older crawl's data in the new format, we want to write a custom script that transforms the data set.

## Deliverables

- Take a version of the old crawl, e.g. [this one](https://github.com/music-os/music-os-data/commit/e985560b5808a731ad58c6e6f2ace6a709e88bfb) and transform it into a music-os-schema complicit schema.
- Important: In the meantime, we have already created transformers for catalog type metadata and sound.xyz. You can find the code: [catalog](https://github.com/music-os/music-os-strategies/blob/main/src/strategies/catalog/transformer.mjs) and [sound](https://github.com/music-os/music-os-strategies/blob/main/src/strategies/soundxyz/transformer.mjs). It may be that you can just copy this code to make the task easier

## Notes

- The script that transforms the old crawler data set into the new crawler data set might never be used again, so we don't need tests or pretty code or whatever. Rather we just want a sizable data set.
- The actual deliverable is the code, along with a `nfts.json` that includes as many music NFTs as we can extract from the old crawl. 
- The task has to be done latest by Friday May 13 2022.

**Comment by il3ven** [comment]
I have understood what needs to be done. Here is how I am planning to do it. Create transformers for various types of data sources like it has been done for sound and catalog then follow the steps outlined by the following pseudo code:
```
for each nft in nfts.json:
  if sourceOf(nft) in known_sources:
     transform[sourceOf(nft)](nft)
  else:
     ignore
```

Does this seem okay?

---

I have question. Should I ignore NFTs that are incomplete or should I assume information freely? If the answer is assume freely then how freely because I can see in [sound transformer](https://github.com/music-os/music-os-strategies/blob/main/src/strategies/soundxyz/transformer.mjs) that you have assumed version. Assuming version is one thing and assuming 90% of the information is another.

For example, here is an incomplete NFT to transform it to music-os compliant schema I'll need to assume/hard-code most of the information. Should I just ignore such NFTs?

```json
[
    {
      "description": "",
      "mimeType": "image/jpeg",
      "name": "taking the piss",
      "version": "zora-20210101"
    },
    "0xabefbc9fd2f806065b4f3c237d4b59d9a97bcac7",
    "641",
    "https://ipfs.fleek.co/ipfs/bafybeibrpfg2k376xmekfoqniljqrkngq2d2so4ugw5rhszgxlsahbvmae"
  ]
```

In my opinion, we should ignore such NFTs. We can transform NFTs where we need to assume only a few fields.

**Comment by TimDaub** [comment]
> Create transformers for various types of data sources like it has been done for sound and catalog then follow the steps outlined by the following pseudo code:

Spoiler alert, the old crawl just contains the metadata of two data sources, those being soundxyz and catalog :) So unless I'm missing something, it may just work with the two `transformer.mjs` files you can find here: https://github.com/music-os/music-os-strategies/tree/main/src/strategies

> Does this seem okay?

LGTM

> Should I ignore NFTs that are incomplete or should I assume information freely?

Yes, please ignore incomplete NFTs. Also, one thing I actually forgot to tell you in the issue description is that catalog mints their music NFTs through Zora. And so the old crawler file in fact contains among catalog music NFTs a lot of completely unrelated Zora NFTs. From what I understand, they differ by their version prefix. For E.g. here is a catalog version prefix: https://github.com/music-os/music-os-data/blob/f25f8206def47641ec4052df360507221d09e105/nfts.json#L82. The one you linked is a Zora prefix "zora-20210101". We can ignore Zora works.

Hope that answered all your questions ✌🏼

**Comment by il3ven** [comment]
I have created a repo with code to transform data. The transformed data is at [transformed_nfts.json](https://github.com/il3ven/music-os-transform/blob/main/transformed_nfts.json). I have converted 8476 NFTs out of total of 17508 NFTs. The remaining NFT were incomplete i.e. not from catalog and soundxyz.

The code is simple and I have re-used the [existing code](https://github.com/music-os/music-os-strategies/tree/main/src/strategies) with minor upgrades. For example, I have calculated [duration](https://github.com/il3ven/music-os-transform/blob/main/transformer/catalog.js#L8) in catalog transformer. I have replaced hardcoded values of `erc721.address` and `erc721.tokenId`.

I ran the transformed data against the schema and observed a failure due to incorrect mime-type. The mime-type at music-os/schema does not include `audio/flac` and `audio/aiff` but the old data contains these types. I assumed the mimetype list to be incomplete and thus [added the two types](https://github.com/il3ven/music-os-transform/blob/main/index.js#L6) to the existing list while checking against the schema.

I did try to take a shot at other things marked as TODO in the code but they will need time to be completed. For [example](https://github.com/il3ven/music-os-transform/blob/main/transformer/catalog.js#L32-L36), fetching file url from tokenURI.

The code is hosted here: https://github.com/il3ven/music-os-transform

**Comment by TimDaub** [comment]
Great job thank you so much! Let's handle the mime type issues in e.g. music-os-schema. In think for the data transformation data set they're negligible.

**Comment by reimertz** [comment]
Awesome work @il3ven and thanks so much! This is perfect and way more data points than we anticipated. Going to be very helpful surfacing bottlenecks with our Strapi integration (already seeing some :))
